name: Publish to PyPI

on:
  release:
    types: [published]

env:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::add-path::$HOME/.poetry/bin"
          source $HOME/.poetry/env
          poetry --version
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build and publish
        run: |
          poetry build
          poetry publish -u atwalsh04 -p ${{ secrets.PYPI_PASSWORD }}